<?php

/**
 * @file
 * Contains hc_kb.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hc_kb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hc_kb module.
    case 'help.page.hc_kb':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
